# Generated by Django 4.2.16 on 2024-11-14 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0002_spr_k0_bmsw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WI_OR_PRE_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day', models.IntegerField(blank=True, null=True)),
                ('time_pb5_msec', models.IntegerField(blank=True, null=True)),
                ('gci_pos_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gci_pos_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gci_pos_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gci_vel_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gci_vel_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gci_vel_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_pos_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_pos_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_pos_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_vel_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_vel_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gse_vel_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_pos_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_pos_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_pos_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_vel_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_vel_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('gsm_vel_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('sun_vector_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('sun_vector_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('sun_vector_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_pos_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_pos_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_pos_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_vel_x', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_vel_y', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('hec_vel_z', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('crn_earth', models.IntegerField(blank=True, null=True)),
                ('long_earth', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('lat_earth', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('long_space', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('lat_space', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
