# Generated by Django 4.2.16 on 2025-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACE_AC_H0_MFI_v01_data',
        ),
        migrations.DeleteModel(
            name='ACE_AC_H0_SWE_v01_data',
        ),
        migrations.DeleteModel(
            name='ACE_AC_OR_SSC_v01_data',
        ),
        migrations.DeleteModel(
            name='DSCOVR_DSCOVR_H0_MAG_v01_data',
        ),
        migrations.DeleteModel(
            name='DSCOVR_DSCOVR_ORBIT_PRE_v01_data',
        ),
        migrations.DeleteModel(
            name='INTERBALL_IT_K0_ELE_v01_data',
        ),
        migrations.DeleteModel(
            name='INTERBALL_IT_K0_MFI_v01_data',
        ),
        migrations.DeleteModel(
            name='INTERBALL_IT_K0_VDP_v01_data',
        ),
        migrations.DeleteModel(
            name='INTERBALL_IT_OR_DEF_v01_data',
        ),
        migrations.DeleteModel(
            name='SPEKTRR_SPR_H1_BMSW_v01_data',
        ),
        migrations.DeleteModel(
            name='SPEKTRR_SPR_K0_BMSW_v01_data',
        ),
        migrations.DeleteModel(
            name='SPEKTRR_SPR_OR_DEF_v01_data',
        ),
        migrations.DeleteModel(
            name='WIND_WI_H0_MFI_v01_data',
        ),
        migrations.DeleteModel(
            name='WIND_WI_K0_SWE_v01_data',
        ),
        migrations.DeleteModel(
            name='WIND_WI_OR_PRE_v01_data',
        ),
    ]
