# Generated by Django 4.2.16 on 2024-11-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0005_wi_k0_swe_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPR_H1_BMSW_data',
        ),
        migrations.DeleteModel(
            name='SPR_K0_BMSW_data',
        ),
        migrations.DeleteModel(
            name='SPR_OR_DEF_data',
        ),
        migrations.DeleteModel(
            name='WI_K0_SWE_data',
        ),
        migrations.DeleteModel(
            name='WI_OR_PRE_data',
        ),
    ]
