# Generated by Django 4.2.16 on 2024-11-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPR_OR_DEF_data',
        ),
    ]
