# Generated by Django 4.2.16 on 2025-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACE_AC_H0_SWE_v01_data',
        ),
    ]
