# Generated by Django 4.2.16 on 2025-11-26 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0013_ace_ac_h0_swe_v01_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE_AC_H1_MFI_v01_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_milliseconds_of_day', models.IntegerField(blank=True, null=True)),
                ('bgsm_bx', models.FloatField(blank=True, null=True)),
                ('bgsm_by', models.FloatField(blank=True, null=True)),
                ('bgsm_bz', models.FloatField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('bgsec_bx', models.FloatField(blank=True, null=True)),
                ('bgsec_by', models.FloatField(blank=True, null=True)),
                ('bgsec_bz', models.FloatField(blank=True, null=True)),
                ('q_flag', models.IntegerField(blank=True, null=True)),
                ('sc_pos_gse_x', models.FloatField(blank=True, null=True)),
                ('sc_pos_gse_y', models.FloatField(blank=True, null=True)),
                ('sc_pos_gse_z', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_x', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_y', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_z', models.FloatField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
