# Generated by Django 4.2.16 on 2024-11-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0014_spr_or_def_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPR_OR_DEF_data',
        ),
    ]
