# Generated by Django 4.2.16 on 2025-11-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0014_ace_ac_h1_mfi_v01_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACE_AC_H0_SWE_v01_data',
        ),
    ]
