# Generated by Django 4.2.16 on 2025-12-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0016_ace_ac_h0_swe_v01_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACE_AC_H0_SWE_v01_data',
        ),
    ]
