# Generated by Django 4.2.16 on 2025-12-05 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0017_delete_ace_ac_h0_swe_v01_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE_AC_H0_SWE_v01_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('np', models.FloatField(blank=True, null=True)),
                ('vp', models.FloatField(blank=True, null=True)),
                ('tpr', models.FloatField(blank=True, null=True)),
                ('alpha_ratio', models.FloatField(blank=True, null=True)),
                ('v_gse_vx', models.FloatField(blank=True, null=True)),
                ('v_gse_vy', models.FloatField(blank=True, null=True)),
                ('v_gse_vz', models.FloatField(blank=True, null=True)),
                ('v_rtn_vr', models.FloatField(blank=True, null=True)),
                ('v_rtn_vt', models.FloatField(blank=True, null=True)),
                ('v_rtn_vn', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_x', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_y', models.FloatField(blank=True, null=True)),
                ('sc_pos_gsm_z', models.FloatField(blank=True, null=True)),
                ('sc_pos_gse_x', models.FloatField(blank=True, null=True)),
                ('sc_pos_gse_y', models.FloatField(blank=True, null=True)),
                ('sc_pos_gse_z', models.FloatField(blank=True, null=True)),
                ('v_gsm_vx', models.FloatField(blank=True, null=True)),
                ('v_gsm_vy', models.FloatField(blank=True, null=True)),
                ('v_gsm_vz', models.FloatField(blank=True, null=True)),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_milliseconds_of_day', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
