# Generated by Django 4.2.16 on 2024-12-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0021_wi_k0_swe_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPR_OR_DEF_data',
        ),
    ]
