# Generated by Django 4.2.16 on 2024-12-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0022_delete_spr_or_def_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WI_K0_SWE_data',
        ),
    ]
