# Generated by Django 4.2.16 on 2024-12-06 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0028_spr_or_def_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WI_K0_SWE_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('delta_time', models.DecimalField(blank=True, decimal_places=12, max_digits=25, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day', models.IntegerField(blank=True, null=True)),
                ('time_pb5_msec', models.IntegerField(blank=True, null=True)),
                ('gap_flag', models.IntegerField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('sc_pos_gse_x', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_gse_y', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_gse_z', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_gsm_x', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_gsm_y', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_gsm_z', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('sc_pos_r', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('dqf', models.IntegerField(blank=True, null=True)),
                ('qf_v', models.IntegerField(blank=True, null=True)),
                ('qf_vth', models.IntegerField(blank=True, null=True)),
                ('qf_np', models.IntegerField(blank=True, null=True)),
                ('qf_ap', models.IntegerField(blank=True, null=True)),
                ('v_gse_x', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gse_y', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gse_z', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gsm_x', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gsm_y', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gsm_z', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gse_p_mag', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gse_p_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('v_gse_p_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('thermal_spd', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('np', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('alpha_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
