# Generated by Django 4.2.16 on 2024-11-14 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dir_path', models.CharField(max_length=300)),
                ('technical_title', models.CharField(blank=True, max_length=50, null=True)),
                ('file_count', models.PositiveIntegerField(blank=True, null=True)),
                ('first_timestamp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_timestamp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('unique_values', models.PositiveIntegerField()),
                ('unique_for_file', models.BooleanField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('addition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('non_record_variant', models.BooleanField()),
                ('is_data', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='load_cdf.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='VariableAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('unique_values', models.PositiveIntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableDataNRV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrv_values', to='load_cdf.variable')),
            ],
            options={
                'unique_together': {('variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VariableAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='load_cdf.variableattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='load_cdf.experimentattribute')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_file_path', models.TextField()),
                ('experiment_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('exploded', models.BooleanField()),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='load_cdf.dynamicmodel')),
                ('nrv_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_field', to='load_cdf.variabledatanrv')),
                ('variable_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.variable')),
            ],
        ),
    ]
