# Generated by Django 4.2.16 on 2025-09-17 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('mission', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('dataset_version', models.CharField(max_length=100)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('logical_source', models.CharField(blank=True, max_length=200, null=True)),
                ('logical_description', models.TextField(blank=True, null=True)),
                ('pi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pi_affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('linked_standard_field', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cdf_file_label', models.CharField(max_length=50, unique=True)),
                ('py_cdf_label', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fillval', models.CharField(blank=True, max_length=50, null=True)),
                ('django_field', models.CharField(max_length=200)),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('datatype', models.CharField(blank=True, max_length=200, null=True)),
                ('dims', models.SmallIntegerField(blank=True, null=True)),
                ('dim_sizes', models.SmallIntegerField(blank=True, null=True)),
                ('dim_values', models.TextField(blank=True, null=True)),
                ('is_displayed', models.BooleanField(blank=True, default=False, null=True)),
                ('data_category', models.CharField(blank=True, max_length=200, null=True)),
                ('catdesc', models.CharField(blank=True, max_length=200, null=True)),
                ('var_notes', models.TextField(blank=True, null=True)),
                ('depend_0', models.CharField(blank=True, max_length=200, null=True)),
                ('display_type', models.CharField(blank=True, max_length=200, null=True)),
                ('fillval', models.CharField(blank=True, max_length=200, null=True)),
                ('output_format', models.CharField(blank=True, max_length=200, null=True)),
                ('lablaxis', models.CharField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, max_length=200, null=True)),
                ('validmin', models.CharField(blank=True, max_length=200, null=True)),
                ('validmax', models.CharField(blank=True, max_length=200, null=True)),
                ('var_logic_type', models.CharField(blank=True, max_length=200, null=True)),
                ('scaletyp', models.CharField(blank=True, max_length=200, null=True)),
                ('scalemin', models.CharField(blank=True, max_length=200, null=True)),
                ('scalemax', models.CharField(blank=True, max_length=200, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='VariableAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_standard_field', models.CharField(blank=True, max_length=100, null=True)),
                ('multipart', models.BooleanField(blank=True, null=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='load_cdf.variableattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_path', models.CharField(max_length=300)),
                ('zip_md5', models.CharField(blank=True, max_length=100, null=True)),
                ('u_tag', models.CharField(max_length=200)),
                ('result_status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Unexpected error'), (2, 'Collision in filenames'), (3, 'Match file error')], default=1)),
                ('file_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='load_cdf.dataset')),
            ],
            options={
                'unique_together': {('u_tag', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('addition', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='load_cdf.upload')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_file_path', models.TextField()),
                ('dataset_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('exploded', models.BooleanField()),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='load_cdf.dynamicmodel')),
                ('variable_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='load_cdf.datasetattribute')),
            ],
        ),
        migrations.CreateModel(
            name='CDFFileStored',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_path', models.CharField(max_length=300)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CDFfiles', to='load_cdf.upload')),
            ],
        ),
    ]
