# Generated by Django 4.2.16 on 2025-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0002_dataset_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='exploded_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
