# Generated by Django 4.2.16 on 2025-08-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0003_alter_upload_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='ziptag',
            new_name='u_tag',
        ),
        migrations.AlterUniqueTogether(
            name='upload',
            unique_together={('u_tag', 'dataset')},
        ),
    ]
