# Generated by Django 4.2.16 on 2025-12-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0003_dynamicfield_exploded_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodel',
            name='files_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmodel',
            name='objects_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
