# Generated by Django 4.2.16 on 2025-12-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0004_dynamicmodel_files_count_dynamicmodel_objects_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmodel',
            name='files_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmodel',
            name='objects_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
