# Generated by Django 4.2.16 on 2025-08-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0004_rename_ziptag_upload_u_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='load_cdf.upload'),
        ),
    ]
