# Generated by Django 4.2.16 on 2025-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0006_rename_dataset_tag_dataset_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfield',
            name='nrv_instance',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='is_data',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='non_record_variant',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='variableattribute',
            name='unique_values',
        ),
        migrations.AddField(
            model_name='datasetattribute',
            name='linked_standard_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='catdesc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='data_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='datatype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='depend_0',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='dim_sizes',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='dims',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='display_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='fillval',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_displayed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='lablaxis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='output_format',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='scalemax',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='scalemin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='scaletyp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='units',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='validmax',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='validmin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_logic_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variableattribute',
            name='linked_standard_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variableattribute',
            name='data_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VariableDataNRV',
        ),
    ]
