# Generated by Django 4.2.16 on 2025-09-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0007_remove_dynamicfield_nrv_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableattribute',
            name='multipart',
            field=models.BooleanField(default=False),
        ),
    ]
