# Generated by Django 4.2.16 on 2025-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0008_variableattribute_multipart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableattribute',
            name='multipart',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
