# Generated by Django 4.2.16 on 2025-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0010_alter_variable_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='var_notes',
        ),
        migrations.AlterField(
            model_name='variable',
            name='catdesc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='data_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='datatype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='depend_0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='dim_sizes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='dims',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='display_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='fillval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='is_displayed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='lablaxis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='output_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='scalemax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='scalemin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='scaletyp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='units',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='validmax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='validmin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_logic_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
