# Generated by Django 4.2.16 on 2025-09-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0011_remove_variable_var_notes_alter_variable_catdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='var_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
