# Generated by Django 4.2.16 on 2025-09-11 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0012_variable_var_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cdf_file_label', models.CharField(max_length=50, unique=True)),
                ('py_cdf_label', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fillval', models.CharField(blank=True, max_length=50, null=True)),
                ('django_field', models.CharField(max_length=200)),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
