# Generated by Django 4.2.16 on 2025-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0013_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='dim_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
